# ans 1
1. TensorFlow offers several data structures for managing and manipulating data, primarily tensors, which are multi-dimensional arrays. Some of the commonly used data structures in TensorFlow include:

   - **Tensors**: Tensors are the fundamental data structure in TensorFlow, similar to multi-dimensional arrays. They can have different ranks (0D scalar, 1D vector, 2D matrix, etc.) and are used for storing and manipulating data. Examples include:

     ```python
     import tensorflow as tf

     scalar = tf.constant(5)  # 0D tensor
     vector = tf.constant([1, 2, 3])  # 1D tensor
     matrix = tf.constant([[1, 2], [3, 4]])  # 2D tensor
     ```

   - **Variables**: TensorFlow variables are used to hold and update trainable parameters in machine learning models. They have an initial value and can change during training. Example:

     ```python
     weight = tf.Variable(initial_value=tf.random.normal((3, 3)))
     ```

   - **Sparse Tensors**: Sparse tensors are used to efficiently represent tensors with a significant number of zero values, often encountered in tasks like natural language processing.

   - **Ragged Tensors**: Ragged tensors are used for sequences of variable-length data, like sequences of words with different lengths in NLP.

   - **TensorArray**: A dynamic-sized array that can store tensors of varying shapes and sizes.

# ans 2
2. TensorFlow Constant vs. TensorFlow Variable:

   - **TensorFlow Constant**: Constants are tensors whose values cannot change during the execution of a TensorFlow program. They are typically used for fixed values like hyperparameters or input data. Once defined, their values remain constant throughout the execution. Example:

     ```python
     import tensorflow as tf

     const_value = tf.constant(5.0)
     ```

   - **TensorFlow Variable**: Variables are tensors that can change their values during training. They are used to store model parameters and gradients that need to be updated and optimized during the training process. Example:

     ```python
     import tensorflow as tf

     initial_value = tf.random.normal((3, 3))
     variable = tf.Variable(initial_value)
     ```


# ans 3
3. Matrix Addition, Multiplication, and Elementwise Operations in TensorFlow:

   - **Matrix Addition**:
     To perform matrix addition in TensorFlow, you can simply use the `tf.add` function or the `+` operator:

     ```python
     import tensorflow as tf

     matrix_a = tf.constant([[1, 2], [3, 4]])
     matrix_b = tf.constant([[5, 6], [7, 8]])

     result = tf.add(matrix_a, matrix_b)  # or result = matrix_a + matrix_b
     ```

   - **Matrix Multiplication**:
     To perform matrix multiplication in TensorFlow, you can use the `tf.matmul` function or the `@` operator (Python 3.5+):

     ```python
     import tensorflow as tf

     matrix_a = tf.constant([[1, 2], [3, 4]])
     matrix_b = tf.constant([[5, 6], [7, 8]])

     result = tf.matmul(matrix_a, matrix_b)  # or result = matrix_a @ matrix_b
     ```

   - **Elementwise Operations**:
     Elementwise operations are operations performed element by element between two tensors of the same shape. You can use standard mathematical operators like `tf.add`, `tf.subtract`, `tf.multiply`, and `tf.divide` for elementwise operations:

     ```python
     import tensorflow as tf

     tensor_a = tf.constant([1, 2, 3])
     tensor_b = tf.constant([4, 5, 6])

     result_add = tf.add(tensor_a, tensor_b)
     result_subtract = tf.subtract(tensor_a, tensor_b)
     result_multiply = tf.multiply(tensor_a, tensor_b)
     result_divide = tf.divide(tensor_a, tensor_b)
     ```

     These operations are applied elementwise, meaning each element in the output tensor is the result of applying the operation to the corresponding elements in the input tensors.

# Taks 1

In [2]:
import tensorflow as tf

# 1. Create a normal matrix A with dimensions 2x2 using random_normal
matrix_A = tf.random.normal(shape=(2, 2), mean=0.0, stddev=1.0)
print("Matrix A:")
print(matrix_A.numpy())

# 2. Create a Gaussian matrix B with dimensions 2x2 using truncated_normal
matrix_B = tf.random.truncated_normal(shape=(2, 2), mean=0.0, stddev=1.0)
print("\nMatrix B:")
print(matrix_B.numpy())

# 3. Create a matrix C with dimensions 2x2 using random.normal
mean = 2.0
stddev = 0.1  # You can adjust the standard deviation (0.x) as needed
matrix_C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)
print("\nMatrix C:")
print(matrix_C.numpy())

# 4. Perform matrix addition between matrix A and matrix B to get matrix D
matrix_D = tf.add(matrix_A, matrix_B)
print("\nMatrix D (Result of Addition):")
print(matrix_D.numpy())

# 5. Perform matrix multiplication between matrix C and matrix D to get matrix E
matrix_E = tf.matmul(matrix_C, matrix_D)
print("\nMatrix E (Result of Multiplication):")
print(matrix_E.numpy())

Matrix A:
[[-1.341613   -0.06263287]
 [ 1.3543245   1.1278253 ]]

Matrix B:
[[-1.1629131   0.8411579 ]
 [-1.2390337  -0.44775876]]

Matrix C:
[[2.1149228 2.1290612]
 [1.9939756 2.053807 ]]

Matrix D (Result of Addition):
[[-2.5045261   0.77852505]
 [ 0.11529076  0.68006647]]

Matrix E (Result of Multiplication):
[[-5.0514183  3.0944235]
 [-4.7571793  2.9490852]]


 # Task 2

In [3]:
import tensorflow as tf

# 1. Create a matrix F with dimensions 2x2 initialized with random values using random_uniform
matrix_F = tf.random.uniform(shape=(2, 2))
print("Matrix F:")
print(matrix_F.numpy())

# 2. Calculate the transpose of matrix F and store the result in matrix G
matrix_G = tf.transpose(matrix_F)
print("\nMatrix G (Transpose of F):")
print(matrix_G.numpy())

# 3. Calculate the elementwise exponential of matrix F and store the result in matrix H
matrix_H = tf.exp(matrix_F)
print("\nMatrix H (Elementwise Exponential of F):")
print(matrix_H.numpy())

# 4. Create a matrix I by concatenating matrix F and matrix G horizontally (axis=1)
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)
print("\nMatrix I (Horizontal Concatenation of F and G):")
print(matrix_I.numpy())

# 5. Create a matrix J by concatenating matrix F and matrix H vertically (axis=0)
matrix_J = tf.concat([matrix_F, matrix_H], axis=0)
print("\nMatrix J (Vertical Concatenation of F and H):")
print(matrix_J.numpy())

Matrix F:
[[0.99016523 0.64997315]
 [0.26505423 0.17406404]]

Matrix G (Transpose of F):
[[0.99016523 0.26505423]
 [0.64997315 0.17406404]]

Matrix H (Elementwise Exponential of F):
[[2.6916792 1.9154894]
 [1.3035016 1.1901318]]

Matrix I (Horizontal Concatenation of F and G):
[[0.99016523 0.64997315 0.99016523 0.26505423]
 [0.26505423 0.17406404 0.64997315 0.17406404]]

Matrix J (Vertical Concatenation of F and H):
[[0.99016523 0.64997315]
 [0.26505423 0.17406404]
 [2.6916792  1.9154894 ]
 [1.3035016  1.1901318 ]]
